// Generated by CoffeeScript 2.3.1
(function() {
  var VERBOSE, fs, path, pug;

  fs = require('fs');

  pug = require('pug');

  path = require('path');

  VERBOSE = process.env.METASERVE_VERBOSE != null;

  module.exports = {
    ext: 'pug',
    default_config: {
      content_type: 'text/html'
    },
    compile: function(filename, config, context, cb) {
      if (VERBOSE) {
        console.log('[PugCompiler.compile]', filename, config);
      }
      return fs.readFile(filename, function(err, file_str) {
        var html, pug_compiler;
        filename = path.join(config.static_dir, '_.pug');
        pug_compiler = pug.compile(file_str, {filename});
        html = pug_compiler(context);
        return cb(err, {
          content_type: config.content_type,
          source: file_str,
          compiled: html
        });
      });
    }
  };

}).call(this);
